services:
  # REMOVED: transcription-api service (transcription now happens in browser)

  # Agent Backend Service (LLM content generation only)
  agent-api:
    build:
      context: ./backend-agent
      dockerfile: Dockerfile.agent
    ports:
      - "8001:8001"
    environment:
      # REMOVED: TRANSCRIPTION_API_URL (no longer needed)
      - LLM_API_URL=https://api.openai.com/v1
      - DEBUG=true
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend (with browser-based transcription)
  frontend:
    build:
      context: ./agent-frontend
      dockerfile: Dockerfile.agent.frontend
    ports:
      - "3000:80"
    environment:
      # REMOVED: REACT_APP_TRANSCRIPTION_API_URL (transcription now in browser)
      - REACT_APP_AGENT_API_URL=http://localhost:8001
      - REACT_APP_DEFAULT_WHISPER_MODEL=onnx-community/whisper-large-v3-turbo_timestamped
      - REACT_APP_ENABLE_WEBGPU=false
      - REACT_APP_ENABLE_MODEL_CACHE=true
    depends_on:
      agent-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge