services:
  # Transcription Backend Service
  transcription-api:
    image: ghcr.io/jockdarock/scribby-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - BASE_URL=https://api.openai.com/v1
      - DEBUG=true
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Agent Backend Service
  agent-api:
    image: ghcr.io/jockdarock/scribby-backend-agent:latest
    ports:
      - "8001:8001"
    environment:
      - TRANSCRIPTION_API_URL=http://transcription-api:8000
      - LLM_API_URL=https://api.openai.com/v1
      - DEBUG=true
    depends_on:
      transcription-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  frontend:
    image: ghcr.io/jockdarock/scribby-agent-frontend:latest
    ports:
      - "3000:80"
    environment:
      - REACT_APP_TRANSCRIPTION_API_URL=http://localhost:8000
      - REACT_APP_AGENT_API_URL=http://localhost:8001
    depends_on:
      transcription-api:
        condition: service_healthy
      agent-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  outputs:
    driver: local
